version: "3.8"

services:
  frontend:
    build:
      context: .
      args:
        API_URL: "http://localhost:3000"
      dockerfile: Dockerfile
    command: sh -c 'npm install && npm run start'
    environment:
      - CHOKIDAR_USEPOLLING=true # Hot Reload を有効にする
    volumes:
      - ./:/frontend
    ports:
      - "8000:3000"
    tty: true
